"""Build the phase-1 warmup corpus: user turns with on-policy assistant turns.

Two steps.

    collect   Stream UltraChat first user turns into a filtered, deduplicated
              prompt pool.

    generate  For each prompt, sample an assistant response from the *unadapted
              base model* and write {question, response} pairs.

Why on-policy: the warmup adapter should learn to model user turns without
also dragging assistant behaviour toward some other model's style. Responses
generated by the same base model being adapted keep the assistant half of the
corpus on-distribution, so the only thing the warmup teaches is user-token
prediction.

Over-length policy: a response that reaches `--max-tokens` is discarded along
with its prompt, and a fresh prompt is drawn from the unused pool. Truncating
instead would teach the model to stop mid-sentence -- which is exactly the
behaviour the trained <|im_end|> is there to protect. Discarding is not neutral:
it removes prompts that elicit long answers, so the corpus skews toward
shorter-answer prompts. The realised accept rate and the resulting mean
response length are both recorded in the metadata sidecar.

Usage::

    python -m umf.warmup.corpus collect --out data/warmup/pool.jsonl --n 30000
    python -m umf.warmup.corpus generate \\
        --pool data/warmup/pool.jsonl \\
        --out data/warmup/warmup_chat.jsonl \\
        --n 20000 --max-tokens 2048
"""

from __future__ import annotations

import argparse
import asyncio
import json
import random
from pathlib import Path

import tinker
from tinker_cookbook import renderers
from tinker_cookbook.completers import TinkerMessageCompleter
from tinker_cookbook.tokenizer_utils import get_tokenizer

from umf import ultrachat
from umf.chat_format import RENDERER_NAME

DEFAULT_MODEL = "Qwen/Qwen3.6-35B-A3B"
SYSTEM_PROMPT = "You are a helpful assistant."
TEMPERATURE = 1.0



# ── collect ───────────────────────────────────────────────────────────


def cmd_collect(args: argparse.Namespace) -> None:
    tokenizer = get_tokenizer(args.model)
    exclude = ultrachat.load_exclusion_keys(args.exclude)
    if exclude:
        print(f"excluding {len(exclude)} prompts seen by a parent adapter")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    rows = [
        {"idx": i, "content": content,
         "n_tokens": len(tokenizer.encode(content, add_special_tokens=False))}
        for i, content in enumerate(
            ultrachat.stream_first_user_turns(tokenizer, args.n, exclude)
        )
    ]

    ultrachat.write_jsonl(out_path, rows)
    lengths = sorted(r["n_tokens"] for r in rows)
    print(
        f"wrote {len(rows)} prompts -> {out_path} "
        f"(tokens mean={sum(lengths) / len(lengths):.0f} p50={lengths[len(lengths) // 2]})"
    )


# ── generate ──────────────────────────────────────────────────────────


async def generate(args: argparse.Namespace) -> None:
    tokenizer = get_tokenizer(args.model)
    renderer = renderers.get_renderer(RENDERER_NAME, tokenizer=tokenizer)
    # Base model, no adapter: these targets must be on-policy for the weights
    # the warmup will actually adapt.
    sampling_client = tinker.ServiceClient().create_sampling_client(base_model=args.model)
    completer = TinkerMessageCompleter(
        sampling_client, renderer, max_tokens=args.max_tokens, temperature=TEMPERATURE
    )

    pool = {r["idx"]: r for r in (json.loads(line) for line in open(args.pool) if line.strip())}
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    discard_path = out_path.with_suffix(".discards.jsonl")

    accepted: dict[int, dict] = {}
    if out_path.exists():  # resume
        for line in open(out_path):
            if line.strip():
                row = json.loads(line)
                accepted[row["pool_idx"]] = row
    discarded: set[int] = set()
    if discard_path.exists():
        for line in open(discard_path):
            if line.strip():
                discarded.add(json.loads(line)["pool_idx"])

    need = args.n - len(accepted)
    print(f"have {len(accepted)}; need {need} more; {len(discarded)} previously discarded")
    if need <= 0:
        finalize(args, tokenizer, pool)
        return

    order = [i for i in sorted(pool) if i not in accepted and i not in discarded]
    random.Random(args.seed).shuffle(order)
    if len(order) < need:
        raise SystemExit(f"only {len(order)} unused prompts for {need} needed rows")

    lock = asyncio.Lock()
    cursor = 0
    n_new = n_discarded = 0

    async def worker(out_f, discard_f) -> None:
        nonlocal cursor, n_new, n_discarded
        while True:
            async with lock:
                if len(accepted) >= args.n or cursor >= len(order):
                    return
                pool_idx = order[cursor]
                cursor += 1
            question = pool[pool_idx]["content"]
            try:
                message = await completer(
                    [
                        renderers.Message(role="system", content=SYSTEM_PROMPT),
                        renderers.Message(role="user", content=question),
                    ]
                )
            except Exception as e:  # transient service error: try another prompt
                print(f"pool_idx={pool_idx} sampling error: {str(e)[:120]}")
                await asyncio.sleep(5)
                continue
            response = message["content"]
            n_tokens = len(tokenizer.encode(response, add_special_tokens=False))
            hit_cap = n_tokens >= args.max_tokens - 8
            async with lock:
                if not response.strip() or hit_cap:
                    discard_f.write(
                        json.dumps(
                            {
                                "pool_idx": pool_idx,
                                "n_tokens": n_tokens,
                                "empty": not response.strip(),
                            }
                        )
                        + "\n"
                    )
                    discard_f.flush()
                    n_discarded += 1
                    continue
                record = {"pool_idx": pool_idx, "question": question, "response": response}
                accepted[pool_idx] = record
                out_f.write(json.dumps(record) + "\n")
                out_f.flush()
                n_new += 1
                if n_new % 500 == 0:
                    print(f"progress: {len(accepted)}/{args.n} accepted, {n_discarded} discarded")

    with open(out_path, "a") as out_f, open(discard_path, "a") as discard_f:
        await asyncio.gather(*[worker(out_f, discard_f) for _ in range(args.concurrency)])
    print(f"added {n_new}, discarded {n_discarded}; total {len(accepted)}/{args.n}")
    finalize(args, tokenizer, pool)


def finalize(args: argparse.Namespace, tokenizer, pool: dict[int, dict]) -> None:
    """Sort, validate, and write the corpus plus a provenance sidecar."""
    out_path = Path(args.out)
    rows = [json.loads(line) for line in open(out_path) if line.strip()]
    if len(rows) < args.n:
        raise SystemExit(f"incomplete: {len(rows)}/{args.n} rows -- rerun to continue")
    rows = rows[: args.n]

    seen: set[int] = set()
    for row in rows:
        if not row["response"].strip():
            raise SystemExit(f"empty response at pool_idx {row['pool_idx']}")
        if row["pool_idx"] in seen:
            raise SystemExit(f"duplicate pool_idx {row['pool_idx']}")
        seen.add(row["pool_idx"])

    with open(out_path, "w") as f:
        for i, row in enumerate(rows):
            f.write(json.dumps({"idx": i, **row}) + "\n")

    discard_path = out_path.with_suffix(".discards.jsonl")
    n_discarded = sum(1 for _ in open(discard_path)) if discard_path.exists() else 0
    response_tokens = [
        len(tokenizer.encode(r["response"], add_special_tokens=False)) for r in rows
    ]
    meta = {
        "model": args.model,
        "adapter": None,
        "renderer": RENDERER_NAME,
        "system_prompt": SYSTEM_PROMPT,
        "temperature": TEMPERATURE,
        "max_tokens": args.max_tokens,
        "over_length_policy": "discard prompt, draw a fresh one from the unused pool",
        "n": len(rows),
        "n_discarded": n_discarded,
        "accept_rate": len(rows) / (len(rows) + n_discarded) if n_discarded else 1.0,
        "response_tokens_mean": sum(response_tokens) / len(response_tokens),
        "pool": str(args.pool),
        "pool_size": len(pool),
        "seed": args.seed,
        "selection_bias_note": (
            "discards are not a random sample: prompts eliciting responses longer "
            f"than {args.max_tokens} tokens are systematically absent"
        ),
    }
    meta_path = out_path.with_suffix(".meta.json")
    meta_path.write_text(json.dumps(meta, indent=2))
    print(
        f"finalized {out_path} ({len(rows)} rows, {n_discarded} discarded, "
        f"accept {meta['accept_rate']:.1%}, mean response "
        f"{meta['response_tokens_mean']:.0f} tok) and wrote {meta_path}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    c = sub.add_parser("collect", help="stream UltraChat first user turns into a prompt pool")
    c.add_argument("--out", required=True)
    c.add_argument("--n", type=int, default=30000)
    c.add_argument(
        "--model", default=DEFAULT_MODEL, help="model whose tokenizer sets the length band"
    )
    c.add_argument(
        "--exclude",
        nargs="*",
        default=[],
        help="jsonl file(s) whose prompts must not appear (e.g. a parent adapter's corpus)",
    )
    c.set_defaults(fn=cmd_collect)

    g = sub.add_parser("generate", help="sample on-policy assistant responses for a pool")
    g.add_argument("--pool", required=True)
    g.add_argument("--out", required=True)
    g.add_argument("--n", type=int, required=True)
    g.add_argument("--model", default=DEFAULT_MODEL)
    g.add_argument("--max-tokens", type=int, default=2048)
    g.add_argument("--concurrency", type=int, default=64)
    g.add_argument("--seed", type=int, default=0)
    g.set_defaults(fn=lambda a: asyncio.run(generate(a)))

    args = parser.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
